# Generated by Django 5.1.2 on 2024-11-29 04:37

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='Book_Genres',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='Book_author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='Book_descripition',
            field=models.TextField(default='Book descripition'),
        ),
        migrations.AddField(
            model_name='books',
            name='Book_image',
            field=models.ImageField(default='', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='books',
            name='Book_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='Book_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='Book_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Books.categories'),
        ),
    ]
