# Generated by Django 5.1.2 on 2024-11-30 05:07

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_categories_books_book_genres_books_book_author_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
                ('cust_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
